AllCops:
  Include:
    - Rakefile
    - config.ru
    - db/migrate/**
  Exclude:
    - bin/**

  RunRailsCops: true

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false
